### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sourcecode-bear** [sourcecode-bear/protospace-33524-2#1]
#URL
https://protospace-33524.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう
（トップページのユーザー名をクリックしたとき、ユーザーの詳細ページに遷移しません）

- [x] ログアウト状態のユーザーは、プロトタイプ新規投稿ページに遷移しようとすると、ログインページにリダイレクトされるようにしましょう

- [x] ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう
（他のユーザーの編集ページに遷移、編集できてしまいます）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sourcecode-bear** [comment]
修正依頼の箇所を完了させました。
変更デプロイ済みとなっておりますので、確認よろしくお願いします。

**Comment by takumi0530** [comment]
@sourcecode-bear さん、ご提出ありがとうございます！！

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページに遷移しようとすると、ログインページにリダイレクトされるようにしましょう**

こちらの２つは修正が確認されました！

しかし、動作の確認中、新たに修正していただきたい箇所がございましたので、以下のご確認をお願いします！

**[修正依頼箇所]**

- [x] **ログイン状態のユーザーだけが、投稿ページへ遷移できること**
現状、ログイン状態のユーザーであっても、「New Proto」をクリックしても投稿画面に遷移せず、トップページに遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

※「ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう」に関しましては、今回確認できなかったため、次回ご提出の際にに併せて確認させていただきます。

**Comment by sourcecode-bear** [comment]
再度、確認をよろしくお願いいたします。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
